# Generated by Django 3.2.7 on 2021-10-02 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_address_customer_addres'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75)),
                ('mrp', models.FloatField()),
                ('selling_price', models.FloatField()),
                ('desc', models.TextField()),
                ('category', models.CharField(max_length=20, verbose_name=(('fr_vegie', 'fruits_vegitables'), ('groc', 'Grocery_staples'), ('dailyess', 'Daily_essentials'), ('frozen', 'Dairy_frozen'), ('homecare', 'Home_care_Personal_care'), ('bedbath', 'Home_care_Personal_care'), ('electronics', 'electronics'), ('footwears', 'footwears')))),
                ('product_image', models.ImageField(upload_to='productimg')),
            ],
        ),
    ]
