# Generated by Django 3.2.7 on 2021-10-02 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_products_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('fr_vegie', 'fruits_vegitables'), ('groc', 'Grocery_staples'), ('dailyess', 'Daily_essentials'), ('frozen', 'Dairy_frozen'), ('homecare', 'Home_care_Personal_care'), ('bedbath', 'Home_care_Personal_care'), ('electronics', 'electronics'), ('footwears', 'footwears')], max_length=20),
        ),
    ]
