# Generated by Django 3.2.7 on 2021-10-14 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_adrs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adrs',
            name='customer',
        ),
    ]
